### ISSUE TITLE
Restructure repo in advance of public launch

### ISSUE THREAD

**Issue by zackkatz** [UseDataKit/SDK#17]
We're planning to split the current repository into two parts:

**SDK:**

- Contains internal functions.
- Includes only primitive DataSources.
- Excludes any extra data sources.

**DataKit Plugin:**

- Houses additional data sources (e.g., Gravity Forms and WS Form).
- Incorporates the user interface.
- Includes the SDK.
- `datakit.php` with WordPress plugin headers.

---------

## TODO

* [ ] Rename `GravityKit/DataKit` repo => `DataKitorg/SDK`
* [x] Add `DataKitorg/DataKit` repo for the plugin
  * [x] Rename `dataviews.php` => `datakit.php`
